# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 17) do

  create_table "comments", :force => true do |t|
    t.column "title",         :string
    t.column "body",          :text
    t.column "user_id",       :integer
    t.column "created_at",    :datetime
    t.column "resource_id",   :integer
    t.column "resource_type", :string
  end

  create_table "definition_versions", :force => true do |t|
    t.column "definition_id", :integer
    t.column "version",       :integer
    t.column "word",          :string
    t.column "description",   :text
    t.column "example",       :text
    t.column "positivevotes", :integer,  :default => 0
    t.column "negativevotes", :integer,  :default => 0
    t.column "updated_by",    :integer
    t.column "updated_at",    :datetime
    t.column "regio",         :integer,  :default => 0
    t.column "rating",        :integer
    t.column "properties",    :string,   :default => "", :null => false
  end

  create_table "definitions", :force => true do |t|
    t.column "word",          :string
    t.column "description",   :text
    t.column "example",       :text
    t.column "positivevotes", :integer,  :default => 0,  :null => false
    t.column "negativevotes", :integer,  :default => 0,  :null => false
    t.column "updated_by",    :integer
    t.column "updated_at",    :datetime
    t.column "regio",         :integer,  :default => 0
    t.column "version",       :integer
    t.column "rating",        :integer
    t.column "properties",    :string,   :default => "", :null => false
  end

  create_table "forums", :force => true do |t|
    t.column "title", :string
    t.column "body",  :text
  end

  create_table "forumtopics", :force => true do |t|
    t.column "title",      :string
    t.column "body",       :text
    t.column "user_id",    :integer
    t.column "created_at", :datetime
    t.column "forum_id",   :integer
  end

  create_table "globalize_countries", :force => true do |t|
    t.column "code",                   :string, :limit => 2
    t.column "english_name",           :string
    t.column "date_format",            :string
    t.column "currency_format",        :string
    t.column "currency_code",          :string, :limit => 3
    t.column "thousands_sep",          :string, :limit => 2
    t.column "decimal_sep",            :string, :limit => 2
    t.column "currency_decimal_sep",   :string, :limit => 2
    t.column "number_grouping_scheme", :string
  end

  add_index "globalize_countries", ["code"], :name => "index_globalize_countries_on_code"

  create_table "globalize_languages", :force => true do |t|
    t.column "iso_639_1",             :string,  :limit => 2
    t.column "iso_639_2",             :string,  :limit => 3
    t.column "iso_639_3",             :string,  :limit => 3
    t.column "rfc_3066",              :string
    t.column "english_name",          :string
    t.column "english_name_locale",   :string
    t.column "english_name_modifier", :string
    t.column "native_name",           :string
    t.column "native_name_locale",    :string
    t.column "native_name_modifier",  :string
    t.column "macro_language",        :boolean
    t.column "direction",             :string
    t.column "pluralization",         :string
    t.column "scope",                 :string,  :limit => 1
  end

  add_index "globalize_languages", ["iso_639_1"], :name => "index_globalize_languages_on_iso_639_1"
  add_index "globalize_languages", ["iso_639_2"], :name => "index_globalize_languages_on_iso_639_2"
  add_index "globalize_languages", ["iso_639_3"], :name => "index_globalize_languages_on_iso_639_3"
  add_index "globalize_languages", ["rfc_3066"], :name => "index_globalize_languages_on_rfc_3066"

  create_table "globalize_translations", :force => true do |t|
    t.column "type",                :string
    t.column "tr_key",              :string
    t.column "table_name",          :string
    t.column "item_id",             :integer
    t.column "facet",               :string
    t.column "built_in",            :boolean, :default => true
    t.column "language_id",         :integer
    t.column "pluralization_index", :integer
    t.column "text",                :text
    t.column "namespace",           :string
  end

  add_index "globalize_translations", ["tr_key", "language_id"], :name => "index_globalize_translations_on_tr_key_and_language_id"
  add_index "globalize_translations", ["table_name", "item_id", "language_id"], :name => "globalize_translations_table_name_and_item_and_language"

  create_table "messages", :force => true do |t|
    t.column "from_user",  :integer
    t.column "to_user",    :integer
    t.column "title",      :string
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "read",       :boolean,  :default => false, :null => false
  end

  create_table "reactions", :force => true do |t|
    t.column "title",         :string
    t.column "body",          :text
    t.column "definition_id", :integer
    t.column "created_by",    :integer
    t.column "created_at",    :datetime
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "details",                   :text
  end

  create_table "voters", :force => true do |t|
  end

  create_table "votes", :force => true do |t|
    t.column "voter_id",      :integer
    t.column "definition_id", :integer
    t.column "value",         :integer
  end

  create_table "wotds", :force => true do |t|
    t.column "definition_id", :integer
    t.column "date",          :date
  end

end
